// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtxucrpdzeokfvshhemd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eHVjcnBkemVva2Z2c2hoZW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTg4NzcsImV4cCI6MjA3MjAzNDg3N30.kxSiCx6UyxJt01wi4tFevUML_D01HsgbmPAYWr_MrrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});